apiVersion: v1
kind: Service
metadata:
  name: edureka-devops-abstergo-corp-svc
  namespace: abstergo
spec:
  type: LoadBalancer
  selector:
    app: edureka-devops-abstergo-corp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000